# Generated by Django 5.0 on 2024-01-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0012_post_gimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gimage',
        ),
        migrations.AddField(
            model_name='post',
            name='art',
            field=models.ImageField(blank=True, null=True, upload_to='art/'),
        ),
    ]
